
server:
  port: 8090
  ip: localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.21.2.103:33106/db_env1?serverTimezone=GMT%2b8
    username: env1
    password: dB@env1.nbyf.cn
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
  ##configuration:
    ##log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: D:\tech_software\java\IDEAWorkSpace\springboot-new\files\
    #path: /home/dev/app/files

